[sink.kafka]
addrs = ["localhost:9092"]
topic = "topik"

[cyclic-replication]
enable = true

[filter]
rules = ['{"db": "vezba", "type": "table"}']

[server]
pd = "pd:2379"
addr = "tidbcdc:8300"
advertise-addr = "tidbcdc:8300"
log-level = "debug"